plugins:
  gofmt:
    enabled: true
  golint:
    enabled: true
  govet:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: true

exclude_patterns:
  - "**/*.golden"
  - "script"
  - "test"
