project_name: rabbitmq-cli-consumer

builds:
  - binary: rabbitmq-cli-consumer
    goos:
      - windows
      - darwin
      - linux

release:
  github:
    owner: corvus-ch
    name: rabbitmq-cli-consumer

archive:
  files:
      - LICENSE.md
      - README.md
      - example.conf
