#!/bin/bash

dir=${WORK_DIR:-.coverage}
mode=${COVER_MODE:-count}
output=${OUTPUT:-c.out}

rm -rf "${dir}"
mkdir "${dir}"

exitCode=0

for pkg in $(go list ./...); do
    name="${dir}/$(echo $pkg | tr / -)"
    f=${name}.cover
    go test -covermode="${mode}" -coverprofile="$f" -coverpkg=./... $@ "${pkg}" || exitCode=1
    if [[ -x ./cc-test-reporter && -e "$f" ]]; then
       ./cc-test-reporter format-coverage --input-type gocov -o "${name}.json" "$f"
    fi
done

echo "mode: $mode" > "${output}"
grep -h -v "^mode:" "${dir}"/*.cover >> "${output}"

exit $exitCode
